In [ ]:
import numpy as np
import pandas as pd
from sklearn import linear_model

In [ ]:
df=pd.read_csv('/hiring.csv')
df

FileNotFoundError: ignored

In [ ]:
reg = linear_model.LinearRegression()

In [ ]:
reg.fit(df[['experience','test_score','interview_score']],df.salary)

LinearRegression()

In [ ]:
reg.predict([[2,9,6]])

/usr/local/lib/python3.7/dist-packages/sklearn/base.py:451: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  "X does not have valid feature names, but"


array([53713.86677124])

In [ ]:
reg.predict([[12,10,10]])

/usr/local/lib/python3.7/dist-packages/sklearn/base.py:451: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  "X does not have valid feature names, but"


array([93747.79628651])

In [ ]:
reg.coef_

array([2922.26901502, 2221.30909959, 2147.48256637])

In [ ]:
reg.intercept_

14992.65144669314