In [ ]:
import numpy as pn
import pandas as pd
from sklearn import linear_model
import matplotlib.pyplot as  plt

In [ ]:
df = pd.read_csv('homeprices.csv')
df

area   price
0  2600  550000
1  3000  565000
2  3200  610000
3  3600  680000
4  4000  725000

In [ ]:
reg = linear_model.LinearRegression()

In [ ]:
reg.fit(df[['area']],df.price)

LinearRegression()

In [ ]:
reg.predict([[3600]])

/usr/local/lib/python3.7/dist-packages/sklearn/base.py:451: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  "X does not have valid feature names, but"


array([669452.05479452])

In [ ]:
reg.coef_

array([135.78767123])

In [ ]:
reg.intercept_

180616.43835616432

In [ ]:
d = pd.read_csv('areas.csv')

In [ ]:
d

area
0   1000
1   1500
2   2300
3   3540
4   4120
5   4560
6   5490
7   3460
8   4750
9   2300
10  9000
11  8600
12  7100

In [ ]:
reg.predict(d)

array([ 316404.10958904,  384297.94520548,  492928.08219178,
        661304.79452055,  740061.64383562,  799808.21917808,
        926090.75342466,  650441.78082192,  825607.87671233,
        492928.08219178, 1402705.47945205, 1348390.4109589 ,
       1144708.90410959])